import type { ComponentType } from 'react';

/**
 * Extension point for interactive figures (planned: TASK-DB-0054).
 *
 * Every paper figure ships four static SVG variants
 * (`NAME.{light,dark}.{wide,tall}.svg`) plus `NAME.data.json` with the plotted
 * numbers, all generated by the same script. `PaperFigure` renders the static
 * variant that matches the theme and width. When a renderer is registered here
 * under the figure's name (or a `chart` fence names one via `renderer`), the
 * page mounts it instead and keeps the static SVG as the print/no-JS/error
 * fallback. Nothing is registered yet.
 */
export type FigureTheme = 'light' | 'dark';
export type FigureLayout = 'wide' | 'tall';

export interface InteractiveFigureProps {
  /** Figure name, e.g. `judges_ranked`. */
  name: string;
  /** URL of `NAME.data.json`. */
  dataUrl: string;
  theme: FigureTheme;
  layout: FigureLayout;
  /** Static SVG for the current theme/layout, to show while loading or on error. */
  fallbackSrc: string;
  alt: string;
}

export const FIGURE_RENDERERS: Record<string, ComponentType<InteractiveFigureProps>> = {};
