#!/usr/bin/env node
/**
 * Split a combined env file into frontend/.env and backend/.env.
 * Usage: pnpm run env:split  (from repo root, services/, or backend/)
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const frontendDir = resolve(root, 'frontend');
const frontendOut = resolve(frontendDir, '.env');
const backendOut = resolve(root, 'backend', '.env');

const candidates = [
  resolve(frontendDir, '.env'),
  resolve(root, '.env'),
  resolve(root, 'backend', '.env'),
].filter((p) => existsSync(p));

if (candidates.length === 0) {
  console.error('No .env found. Copy frontend/.env.example and backend/.env.example first.');
  process.exit(1);
}

const src = candidates[0];
const raw = readFileSync(src, 'utf8');
const hasVite = raw.split('\n').some((l) => l.trim().startsWith('VITE_'));
const hasBackend = raw.split('\n').some((l) => {
  const t = l.trim();
  if (!t || t.startsWith('#')) return false;
  const key = t.slice(0, t.indexOf('=')).trim();
  return key && !key.startsWith('VITE_');
});

if (!hasVite || !hasBackend) {
  console.error(
    `Expected both VITE_* and backend keys in ${src}. Use separate frontend/.env and backend/.env instead.`,
  );
  process.exit(1);
}

mkdirSync(frontendDir, { recursive: true });

const frontend = [];
const backend = [];
for (const line of raw.split('\n')) {
  const t = line.trim();
  if (!t || t.startsWith('#')) {
    frontend.push(line);
    continue;
  }
  const i = t.indexOf('=');
  if (i <= 0) {
    frontend.push(line);
    continue;
  }
  const key = t.slice(0, i).trim();
  if (key.startsWith('VITE_')) {
    frontend.push(line);
  } else {
    backend.push(line);
  }
}

writeFileSync(frontendOut, `${frontend.join('\n').trim()}\n`, 'utf8');
writeFileSync(
  backendOut,
  `# Generated by scripts/split-env.mjs\n${backend.join('\n').trim()}\n`,
  'utf8',
);

console.log(`Read ${src}`);
console.log('Wrote frontend keys → frontend/.env');
console.log('Wrote backend keys  → backend/.env');
if (src === resolve(root, '.env')) {
  console.log('You can delete the legacy repo-root .env if everything looks correct.');
}
